[project]
name = 'Multiversal-Energy-Grid'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.energy-transfer]
path = 'contracts/energy-transfer.clar'
clarity_version = 2
epoch = 2.5

[contracts.grid-stability]
path = 'contracts/grid-stability.clar'
clarity_version = 2
epoch = 2.5

[contracts.universe-registry]
path = 'contracts/universe-registry.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
